# Prompt
prompt: components/prompt/feedback_only.md
prompt_input:  # key : path mapping
  instruction: task/taboo_reformulate/instruction.md
  feedback: components/feedback/default.md
  
# CLI
name: taboo_reformulate
description: |
  Explain the given word without using any of the words in the provided taboo list.
