# Prompt
prompt: components/prompt/feedback_only.md
prompt_input:  # key : path mapping
  instruction: task/taboo_reformulate/instruction.md
  feedback: components/feedback/default.md
  
# CLI
name: taboo_reformulate
description: |
  Reformulate the given text to avoid using any of the words in the provided taboo list.
  The reformulated text should maintain the original meaning while adhering to the taboo restrictions.
